#include <iostream>
using namespace std;
int main()
{
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand(); cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 cout<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand()<<rand();
 system ("pause");
 }
